### ISSUE TITLE
blank versions reported

### ISSUE THREAD

**Issue by usjpaq** [baruchiro/dll-props#9]
I built from the master branch. Some minor issues:

1) no help
⇒   dll-props --help                                                                                                                                                                                    
Unhandled exception. System.IO.FileNotFoundException: /Users/usjpaq/Downloads/Waters-2/Extractor/--help
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at DllProps.Tool.Program.Main(String[] args) in /home/runner/work/dll-props/dll-props/DllProps.Tool/Program.cs:line 10
[1]    23854 abort      dll-props --help

2) crash on no args
⇒  dll-props                                                                                                                                                                                           
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DllProps.Tool.Program.Main(String[] args) in /home/runner/work/dll-props/dll-props/DllProps.Tool/Program.cs:line 10
[1]    23891 abort      dll-props
usjpaq:Downloads/Waters-2/Extractor|

3) fails to show versions
⇒  dll-props my.exe                                                                                                                                                 
Company: 
Copyright: 
FileVersion: 
ProductVersion: 
Description: 

Same file, from a windows machine:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/76955012/235930099-d0b6b652-713e-4972-a848-788e30e5f61c.png">

**Comment by baruchiro** [comment]
Hi, thank you for reporting!

Actually, it is an old project, do you want to fix it?

**Comment by usjpaq** [comment]
Apologies, but I do not have the bandwidth at this time. I did run it in the debugger, the object returned by `FileVersionInfo.GetVersionInfo` does not return the version info. Seems to be related to https://stackoverflow.com/questions/63773485/c-sharp-fileversioninfo-getversioninfo-not-working-on-mac-os
